import { Response } from 'express';
import prisma from '../utils/prisma';
import { AppError, asyncHandler } from '../middleware/errorHandler';
import { AuthRequest } from '../middleware/auth';
import { parseNaturalLanguageQuery, generateDashboardInsights, validateCSVWithAI, generateReport } from '../services/ai.service';
import { logger } from '../utils/logger';

// ─── POST /ai/search — Natural Language Search ──────────────────────────────

export const aiSearch = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const { query } = req.body;

    if (!query || typeof query !== 'string' || query.trim().length === 0) {
      throw new AppError('Search query is required', 400);
    }

    if (query.length > 500) {
      throw new AppError('Query too long (max 500 characters)', 400);
    }

    // Get available stores for context
    const storeFilter = req.user?.role === 'STORE_MANAGER' && req.user.storeId
      ? { id: req.user.storeId }
      : {};

    const stores = await prisma.store.findMany({
      where: storeFilter,
      select: { id: true, storeName: true }
    });

    // Parse natural language to structured filters
    const filters = await parseNaturalLanguageQuery(query, stores);

    // Build Prisma where clause from parsed filters
    const where: any = {};

    if (req.user?.role === 'STORE_MANAGER' && req.user.storeId) {
      where.storeId = req.user.storeId;
    } else if (filters.storeId) {
      where.storeId = filters.storeId;
    }

    if (filters.sku) where.sku = { contains: filters.sku };
    if (filters.productName) where.productName = { contains: filters.productName };

    if (filters.dateFrom || filters.dateTo) {
      where.date = {};
      if (filters.dateFrom) where.date.gte = new Date(filters.dateFrom);
      if (filters.dateTo) where.date.lte = new Date(filters.dateTo);
    }

    if (filters.minPrice || filters.maxPrice) {
      where.price = {};
      if (filters.minPrice) where.price.gte = filters.minPrice;
      if (filters.maxPrice) where.price.lte = filters.maxPrice;
    }

    const orderBy = filters.sortBy
      ? { [filters.sortBy]: filters.sortOrder || 'desc' }
      : { date: 'desc' as const };

    const [records, total] = await Promise.all([
      prisma.pricingRecord.findMany({
        where,
        take: 50,
        orderBy,
        include: {
          store: { select: { storeId: true, storeName: true, country: true } }
        }
      }),
      prisma.pricingRecord.count({ where })
    ]);

    logger.info(`AI search by ${req.user?.email}: "${query}" → ${total} results`);

    res.json({
      status: 'success',
      data: {
        records,
        total,
        parsedFilters: filters,
        originalQuery: query
      }
    });
  }
);

// ─── GET /ai/insights — Dashboard Insights ──────────────────────────────────

export const getInsights = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const insights = await generateDashboardInsights(
      req.user!.role,
      req.user?.storeId
    );

    res.json({
      status: 'success',
      data: { insights }
    });
  }
);

// ─── POST /ai/validate-csv — AI CSV Validation ──────────────────────────────

export const validateCSV = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const { rows } = req.body;

    if (!rows || !Array.isArray(rows) || rows.length === 0) {
      throw new AppError('CSV rows data is required', 400);
    }

    if (rows.length > 5000) {
      throw new AppError('Too many rows for validation (max 5000)', 400);
    }

    const stores = await prisma.store.findMany({ select: { storeId: true } });
    const storeIds = stores.map(s => s.storeId);

    const validation = await validateCSVWithAI(rows, storeIds);

    logger.info(`AI CSV validation by ${req.user?.email}: ${rows.length} rows, valid=${validation.isValid}`);

    res.json({
      status: 'success',
      data: { validation }
    });
  }
);

// ─── POST /ai/report — Natural Language Report Generation ───────────────────

export const generateAIReport = asyncHandler(
  async (req: AuthRequest, res: Response) => {
    const { query } = req.body;

    if (!query || typeof query !== 'string' || query.trim().length === 0) {
      throw new AppError('Report query is required', 400);
    }

    if (query.length > 500) {
      throw new AppError('Query too long (max 500 characters)', 400);
    }

    const report = await generateReport(
      query.trim(),
      req.user!.role,
      req.user?.storeId
    );

    logger.info(`AI report generated by ${req.user?.email}: "${query}"`);

    res.json({
      status: 'success',
      data: { report }
    });
  }
);
